# Generated by Django 2.0.6 on 2018-07-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='img/default.png', null=True, upload_to='teacher/%Y/%m', verbose_name='头像'),
        ),
    ]
