# Generated by Django 2.0.6 on 2018-07-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180712_0259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='cn_subtitle',
        ),
        migrations.RemoveField(
            model_name='video',
            name='en_subtitle',
        ),
    ]
