# Generated by Django 2.0.6 on 2018-07-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20180715_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='is_banner',
            new_name='or_banner',
        ),
    ]
