# Generated by Django 2.0.6 on 2018-07-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20180715_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='or_banner',
            new_name='is_banner',
        ),
    ]
