# Generated by Django 2.0.6 on 2018-07-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20180716_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='like_nums',
            field=models.IntegerField(default=0, verbose_name='收藏数'),
        ),
    ]
