# Generated by Django 2.0.6 on 2018-07-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_course_like_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='click_nums',
            field=models.CharField(default=0, max_length=100, verbose_name='点击数'),
        ),
    ]
