# Generated by Django 2.0.6 on 2018-07-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20180721_0932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name': '课程类别', 'verbose_name_plural': '课程类别'},
        ),
        migrations.AlterField(
            model_name='video',
            name='click_nums',
            field=models.IntegerField(default=0, max_length=100, verbose_name='点击数'),
        ),
    ]
