# Generated by Django 2.0.6 on 2018-07-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20180722_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
    ]
