# Generated by Django 2.0.7 on 2018-07-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20180722_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='点击数'),
        ),
    ]
