# Generated by Django 2.0.6 on 2018-07-21 10:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0012_auto_20180721_0932'),
        ('operation', '0002_auto_20180712_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=200, verbose_name='评论')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='course.Video', verbose_name='课程')),
            ],
            options={
                'verbose_name': '课程评论',
                'verbose_name_plural': '课程评论',
            },
        ),
        migrations.RemoveField(
            model_name='coursecomments',
            name='course',
        ),
        migrations.RemoveField(
            model_name='coursecomments',
            name='user',
        ),
        migrations.DeleteModel(
            name='CourseComments',
        ),
    ]
